/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Taylan Unal
 */
public class jFinanceFrame extends javax.swing.JFrame {

    /**
     * Creates new form jFinanceFrame
     */
    public jFinanceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomSchedulerTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ReserveRoom_JPanel = new javax.swing.JPanel();
        ReserveRoom_Faculty = new javax.swing.JLabel();
        ReserveRoom_FacultyComboBox = new javax.swing.JComboBox<>();
        ReserveRoom_Date = new javax.swing.JLabel();
        ReserveRoom_DateComboBox = new javax.swing.JComboBox<>();
        ReserveRoom_SeatsRequired = new javax.swing.JLabel();
        ReserveRoom_SeatsTextField = new javax.swing.JTextField();
        ReserveRoom_SubmitButton = new javax.swing.JButton();
        ReserveRoom_InputTextArea = new javax.swing.JTextArea();
        ReserveRoom_InputLabel = new javax.swing.JLabel();
        ReserveRoom_ConfirmationLabel = new javax.swing.JLabel();
        ReserveRoom_ConfirmationTextArea = new javax.swing.JTextArea();
        addAccounts = new javax.swing.JPanel();
        Savings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Checking = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        Credit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        Loans = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        addAccountsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RoomSchedulerTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        RoomSchedulerTitle.setForeground(new java.awt.Color(204, 0, 0));
        RoomSchedulerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomSchedulerTitle.setText("jFinance");

        ReserveRoom_Faculty.setText("Faculty: ");

        ReserveRoom_Date.setText("Date: ");

        ReserveRoom_SeatsRequired.setText("Seats Required: ");

        ReserveRoom_SeatsTextField.setColumns(3);

        ReserveRoom_SubmitButton.setText("Submit");
        ReserveRoom_SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveRoom_SubmitButtonActionPerformed(evt);
            }
        });

        ReserveRoom_InputTextArea.setEditable(false);
        ReserveRoom_InputTextArea.setColumns(20);
        ReserveRoom_InputTextArea.setRows(5);

        ReserveRoom_InputLabel.setText("Input Information");

        ReserveRoom_ConfirmationLabel.setText("Reservation Information");

        ReserveRoom_ConfirmationTextArea.setEditable(false);
        ReserveRoom_ConfirmationTextArea.setColumns(20);
        ReserveRoom_ConfirmationTextArea.setRows(5);

        javax.swing.GroupLayout ReserveRoom_JPanelLayout = new javax.swing.GroupLayout(ReserveRoom_JPanel);
        ReserveRoom_JPanel.setLayout(ReserveRoom_JPanelLayout);
        ReserveRoom_JPanelLayout.setHorizontalGroup(
            ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReserveRoom_InputLabel)
                            .addComponent(ReserveRoom_InputTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                                .addComponent(ReserveRoom_ConfirmationLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ReserveRoom_ConfirmationTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReserveRoom_Faculty)
                            .addComponent(ReserveRoom_Date)
                            .addComponent(ReserveRoom_SeatsRequired))
                        .addGap(18, 18, 18)
                        .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReserveRoom_FacultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReserveRoom_DateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReserveRoom_SeatsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                    .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ReserveRoom_SubmitButton)))
                .addGap(22, 22, 22))
        );
        ReserveRoom_JPanelLayout.setVerticalGroup(
            ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReserveRoom_Faculty)
                    .addComponent(ReserveRoom_FacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReserveRoom_Date)
                    .addComponent(ReserveRoom_DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReserveRoom_SeatsRequired)
                    .addComponent(ReserveRoom_SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReserveRoom_SubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReserveRoom_JPanelLayout.createSequentialGroup()
                        .addComponent(ReserveRoom_ConfirmationLabel)
                        .addGap(185, 185, 185))
                    .addGroup(ReserveRoom_JPanelLayout.createSequentialGroup()
                        .addComponent(ReserveRoom_InputLabel)
                        .addGap(3, 3, 3)
                        .addGroup(ReserveRoom_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReserveRoom_InputTextArea)
                            .addComponent(ReserveRoom_ConfirmationTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reserve Room", ReserveRoom_JPanel);

        addAccounts.setName(""); // NOI18N
        addAccounts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Savings.setBorder(javax.swing.BorderFactory.createTitledBorder("Checking Accounts"));

        jLabel1.setText("Balance:");

        jLabel2.setText("Interest Rate:");

        jTextField1.setText("$12,345");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("x.x%");

        javax.swing.GroupLayout SavingsLayout = new javax.swing.GroupLayout(Savings);
        Savings.setLayout(SavingsLayout);
        SavingsLayout.setHorizontalGroup(
            SavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavingsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addContainerGap())
        );
        SavingsLayout.setVerticalGroup(
            SavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavingsLayout.createSequentialGroup()
                .addGroup(SavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addAccounts.add(Savings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 50));

        Checking.setBorder(javax.swing.BorderFactory.createTitledBorder("Savings Accounts"));

        jLabel5.setText("Balance:");

        jLabel6.setText("Interest Rate:");

        jTextField5.setText("$12,345");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setText("x.x%");

        javax.swing.GroupLayout CheckingLayout = new javax.swing.GroupLayout(Checking);
        Checking.setLayout(CheckingLayout);
        CheckingLayout.setHorizontalGroup(
            CheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckingLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addContainerGap())
        );
        CheckingLayout.setVerticalGroup(
            CheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckingLayout.createSequentialGroup()
                .addGroup(CheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addAccounts.add(Checking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        Credit.setBorder(javax.swing.BorderFactory.createTitledBorder("Credit Accounts"));

        jLabel7.setText("Balance:");

        jLabel8.setText("Interest Rate:");

        jTextField7.setText("$12,345");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setText("x.x%");

        javax.swing.GroupLayout CreditLayout = new javax.swing.GroupLayout(Credit);
        Credit.setLayout(CreditLayout);
        CreditLayout.setHorizontalGroup(
            CreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addContainerGap())
        );
        CreditLayout.setVerticalGroup(
            CreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditLayout.createSequentialGroup()
                .addGroup(CreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addAccounts.add(Credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 50));

        Loans.setBorder(javax.swing.BorderFactory.createTitledBorder("Loan Accounts"));

        jLabel9.setText("Balance:");

        jLabel10.setText("Interest Rate:");

        jTextField9.setText("$12,345");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.setText("x.x%");

        javax.swing.GroupLayout LoansLayout = new javax.swing.GroupLayout(Loans);
        Loans.setLayout(LoansLayout);
        LoansLayout.setHorizontalGroup(
            LoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoansLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addContainerGap())
        );
        LoansLayout.setVerticalGroup(
            LoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoansLayout.createSequentialGroup()
                .addGroup(LoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addAccounts.add(Loans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 430, 50));

        addAccountsButton.setText("Submit");
        addAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountsButtonActionPerformed(evt);
            }
        });
        addAccounts.add(addAccountsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jTabbedPane1.addTab("Add Accounts", addAccounts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(RoomSchedulerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RoomSchedulerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReserveRoom_SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveRoom_SubmitButtonActionPerformed
        //CREATE RESERVATION FOR THE FACULTY, WITH ROOM (based on seats), ON DATE.

        String facultyName = ReserveRoom_FacultyComboBox.getSelectedItem().toString();
        Integer seatsRequired = Integer.parseInt(ReserveRoom_SeatsTextField.getText());
        String dateString = ReserveRoom_DateComboBox.getSelectedItem().toString(); //have to convert to string
        Date reserveDate = Date.valueOf(ReserveRoom_DateComboBox.getSelectedItem().toString()); //used to search SQL
        Timestamp currentTimestamp = new Timestamp(Calendar.getInstance().getTime().getTime());
        //DISPLAY INPUTTED INFORMATION
        ReserveRoom_InputTextArea.setText("Faculty Name: "+facultyName+ "\nDate: " + dateString + "\nSeats: " + seatsRequired);
        //END INPUT

        //START CREATING RESERVATION
        ArrayList<String> bestRooms = RoomQueries.getBestRooms(seatsRequired); //list of possible rooms for teacher.
        ArrayList<String> roomsReservedOnDate = ReservationQueries.getRoomsReservedByDate(reserveDate); // used to check if room selected is reserved.
        if(bestRooms.isEmpty()){ //check if roomList is empty (aka there are no rooms for the teacher)
            WaitlistQueries.addWaitlistEntry(facultyName, reserveDate, seatsRequired, currentTimestamp);
            ReserveRoom_ConfirmationTextArea.setText("There are no rooms avaliable with enough seats.\nYou've been added to the waitlist.\n"+
                "Faculty Name: " + facultyName + "\nDate: " + dateString + "\nSeats: " + seatsRequired + "\nTimestamp: "+ currentTimestamp);
        }
        else if(roomsReservedOnDate.contains(bestRooms.get(0))){//if the current room has a reservation, then add to waitlist
            WaitlistQueries.addWaitlistEntry(facultyName, reserveDate, seatsRequired, currentTimestamp);
            ReserveRoom_ConfirmationTextArea.setText("There are no rooms available on this date.\nYou've been added to the waitlist.\n"+
                "Faculty Name: " + facultyName + "\nDate: " + dateString + "\nSeats: " + seatsRequired + "\nTimestamp: "+ currentTimestamp);
        }
        else{//normal case, no need for waitlist.
            String bestRoom = RoomQueries.getBestRooms(seatsRequired).get(0);// GETS ROOM
            ReservationQueries.addReservationEntry(facultyName, bestRoom, reserveDate, seatsRequired, currentTimestamp); //input necessary data
            //DISPLAYING RESERVATION CONFIRMATION
            ReserveRoom_ConfirmationTextArea.setText("Reservation Created For: \nFaculty Name: " + facultyName + "\nRoom: " + bestRoom +"\nDate: " + dateString + "\nSeats: " + seatsRequired + "\nTimestamp: "+ currentTimestamp);
        }
    }//GEN-LAST:event_ReserveRoom_SubmitButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void addAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAccountsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFinanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFinanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFinanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFinanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFinanceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Checking;
    private javax.swing.JPanel Credit;
    private javax.swing.JPanel Loans;
    private javax.swing.JLabel ReserveRoom_ConfirmationLabel;
    private javax.swing.JTextArea ReserveRoom_ConfirmationTextArea;
    private javax.swing.JLabel ReserveRoom_Date;
    private javax.swing.JComboBox<String> ReserveRoom_DateComboBox;
    private javax.swing.JLabel ReserveRoom_Faculty;
    private javax.swing.JComboBox<String> ReserveRoom_FacultyComboBox;
    private javax.swing.JLabel ReserveRoom_InputLabel;
    private javax.swing.JTextArea ReserveRoom_InputTextArea;
    private javax.swing.JPanel ReserveRoom_JPanel;
    private javax.swing.JLabel ReserveRoom_SeatsRequired;
    private javax.swing.JTextField ReserveRoom_SeatsTextField;
    private javax.swing.JButton ReserveRoom_SubmitButton;
    private javax.swing.JLabel RoomSchedulerTitle;
    private javax.swing.JPanel Savings;
    private javax.swing.JPanel addAccounts;
    private javax.swing.JButton addAccountsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
